### PR TITLE
WIP Fix for blank windows from Chromium content

### LINKED ISSUE #87: Many blank windows
This could be related to #72 but doesn't seem to have anything to do with DX12, so I doubt it.

image

This is every window that survives the filtering process described in #86. Some of them work fine, but most windows come out as all zeros (black and zero alpha.) In some cases (like the Steam client) some of content is captured, but most is not. One common thread seems to be that most of these windows (Hangouts, Chrome, a few windows from the Steam client) are all showing web content from Chromium.

The exception from that is the VR View window from SteamVR, which is a shared texture rendered by Qt.

Any idea what might be going on here? Can you repro the problem with the Steam client? It should be easy to get your hands on...

### PR DESCRIPTION
**Pull request by JoeLudwig**
Fixes #87

It seems that when using Windows 10, or when using Aero on Windows 8.0 and above, PrintWindow will capture windows where D3D is used to render content. BitBlt fails in those cases, but is still useful as a backup because PrintWindow won't work for all windows either.

### CODE REVIEW

**Comment by JoeLudwig** [comment]
@smasherprog I don't think this is actually ready to merge yet.

Some things to address:
* It might still be desirable to capture popup windows for things like tooltips and popup menus. The code is currently commented out because it also tries to capture child windows, which is unnecessary.
* What is the minimum Windows version that screen_capture_lite is expected to run on? If it's Win10, this code is fine. If it's Vista or below this code needs additional checks for windows version and whether or not Aero is enabled.  (Do you have existing routines in this library to test for whether or not Aero is enabled or to retrieve the Windows version? If not, where would you like me to add those?)

**Comment by smasherprog** [comment]
Win10 is minimum.
Checking this out now... Thanks for the PR

**Comment by smasherprog** [comment]
Yeah, I didnt even think about popups. Thats an interesting topic as where would the popup go if it falls outside the bounds of the main window being captured? I think in that case it should be cut off to fit in the bounds of the window being captured.  Thoughts?

This is the first time i have seen the PrintWindow function. Looks like that will allow capturing of windows so i am looking into if there are any performance concerns with printwindow or if it will "just work". If printwindow has some perf issues we would need to see if it can be called only if needed and use bitblt first.
Have u looked into any of this?

**Comment by Electric-Turtle** [comment]
@JoeLudwig , I just pulled your branch into my project (which submodules screen_capture_lite). It appears to fix the issue I raised in #72 (looks like my hypothesis that DirectX12 causing the issue is not entirely correct).  The only new behavior i see is the presence of a very small vertical black stripe showing up on the left-hand side of the captured frames (see below).  I can live with that, pretty easy to crop the black stripe out, but I just wanted to make you aware in case that's indicative of some other problem you may be facing.
black_stripe

**Comment by smasherprog** [comment]
okay cool if this works, then ill merge it into master. I havent been spending alot of time in this project so i am really looking for others to help in this regard.

**Comment by smasherprog** [comment]
Checked the code out and it looks good to me. Thanks for the PR!!!

**Pull request merged**
